# https://docs.travis-ci.com/user/job-lifecycle/
os: linux
dist: xenial
language: go

notifications:
  email:
    on_success: never
    on_failure: always

env:
  - LUA="lua5.1" PYTHON="python3"

addons:
  apt:
    packages:
      - luajit
      - luarocks
      - jq
      - python3
      - python3-pip

before_install:
  - sudo apt-get update

before_script:
  - luarocks install --local --lua-version=5.1 luacheck
  - luarocks install --local --lua-version=5.1 luafilesystem
  - luarocks install --local --lua-version=5.1 busted
  - luarocks install --local --lua-version=5.1 xml2lua
  - luarocks install --local --lua-version=5.1 penlight
  - luarocks install --local --lua-version=5.1 bitlib
  - luarocks install --local --lua-version=5.1  luasec
  - luarocks install --local --verbose --lua-version=5.1 lanes 3.14.0
  - luarocks install --local --lua-version=5.1 copas
  - luarocks install --local --lua-version=5.1 copas-async
  - luarocks install --local --lua-version=5.1 luacov
  - luarocks install --local --lua-version=5.1 cluacov
  - luarocks install --local --lua-version=5.1 luacov-coveralls
  - pip3 install mistune==2.0.0rc1

script:
  - eval `luarocks --lua-version=5.1 path`
  - /home/travis/.luarocks/bin/luacheck . --no-color -q
  - /home/travis/.luarocks/bin/busted --lua=lua5.1 -c -o gtest .

deploy:
  provider: script
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  script: bash $TRAVIS_BUILD_DIR/.tools/deploy.sh
  on:
    branch: master

after_script:
  - /home/travis/.luarocks/bin/luacov-coveralls -v -t $COVERALLS_TOKEN